name: CI/CD Pipeline to Docker Hub

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build Test and Deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install
        run: make install
      - name: Lint
        run: make lint
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}
      - name: Build and Push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_HUB_USERNAME }}/flight-delay-project-fall22:yml_git_hub_run_${{ github.run_number }}, ${{ secrets.DOCKER_HUB_USERNAME }}/flight-delay-project-fall22:latest