name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . -f Dockerfile -t airline-project-fall22:$(date +%s)
    - name: Publish to Dockerhub
      uses: docker/build-push-action@v2
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ajkroening/test
        tags: latest, ${{ github.run_number }}
    - name: Run the Docker image
      run: docker run -d -p 80:80 airline-project-fall22:$(date +%s)
    - name: Push the Docker image
      run: docker push ajkroening/test:latest